### PR TITLE
🏹 QM Pytest

### PR DESCRIPTION
**Pull request by mrharpo**
# qm/pytest
Migrates CI test to use [qm/.github/.github/workflows/pytest.yml](https://github.com/quaternionmedia/.github/blob/main/.github/workflows/pytest.yml)

### CODE REVIEW

**Review by subcontrabass — APPROVED** [review]
Tests ahoy. Loving the standardization

**Comment by mrharpo** [comment]
This should work once we publish to pypi with [otto#23](https://github.com/quaternionmedia/otto/issues/23)

Holding until then.

**Review by CameronRWest — CHANGES_REQUESTED** [review]
I tried the tests/nox but i may not have had it setup correctly. I'll take a look tomorrow. 

but could the README get updated with the test command(s) to run? or the noxfile location.

**Comment by mrharpo** [comment]
@CameronRWest Definitely should update the readme!

The steps should be:
```bash
# install pdm
pip install pdm

# create a local virtual environment
pdm venv create

# Use that local virtual environmet
pdm use

# Install the dependencies
pdm install

# Activate your local virtual environment
eval $(pdm venv activate)

# Run the tests
pytest

# Run the server
uvicorn alfred.main:app
```

**Review by subcontrabass — APPROVED** [review]
Nox is working great! Still having issues with pdm

**Review by CameronRWest — APPROVED** [review]
looks good!

**Review by subcontrabass — APPROVED** [review]

**Pull request merged**
